/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class SSLContextSetupTest {
    @Test
    void remoteCallSucceeds() throws Exception {
        SSLContextSetup classUnderTest = new SSLContextSetup();
        assertEquals(classUnderTest.callRemote("https://google.com/", null, null), 200);
    }
}
